---
# tasks file for aws_create_vpc

#- hosts: localhost
#  module_defaults:
#    group/aws:
#      aws_access_key: '{{ vault_aws_access_key }}'
#      aws_secret_key: '{{ vault_aws_secret_key }}'
#      region: '{{ aws_region }}'

- name: Create VPC
  include_tasks: create_vpc.yaml

- name: Create IGW
  include_tasks: create_IGW.yaml

- name: Create Security Group
  include_tasks: create_security_group.yaml

